#!/bin/bash
# Wrapper skript pre ESLint - deleguje na npm script lint z package.json
export NODE_PATH=/opt/int/node_modules
export PATH=/opt/int/node_modules/.bin:$PATH

if [ ! -d "/src/int/node_modules" ]; then
  ln -s /opt/int/node_modules /src/int/node_modules
fi

if [ $# -eq 0 ]; then
  exec npx eslint "src/**/*.ts"
else
  exec npx eslint "$@"
fi
