#!/bin/bash
# Wrapper skript pre Prettier - deleguje na npm script format z package.json
export NODE_PATH=/opt/int/node_modules
export PATH=/opt/int/node_modules/.bin:$PATH

exec npm run format -- "$@"
