#!/bin/bash
# Wrapper skript pre Ruff

# Workaround pre Windows/WSL host Docker volumes, kde nie je mozne upravit
# executable permissions a sposobuje to EXE002 error vo vsetkych suboroch 
IGNORE_FLAG=""
if [[ "$1" == "check" || $# -eq 0 ]]; then
    IGNORE_FLAG="--ignore=EXE002"
fi

# Ak nie je zadana cesta, kontroluj len src
if [[ $# -eq 0 ]]; then
	exec ruff check $IGNORE_FLAG src
fi

if [[ "$1" == "check" || "$1" == "format" ]]; then
	has_target=false

	for arg in "${@:2}"; do
		if [[ "$arg" != -* ]]; then
			has_target=true
			break
		fi
	done

	if [[ "$has_target" == "false" ]]; then
		exec ruff "$1" $IGNORE_FLAG "${@:2}" src
	fi
fi

if [[ "$1" == "check" ]]; then
    exec ruff "$1" $IGNORE_FLAG "${@:2}"
else
    exec ruff "$@"
fi
